name = "Main"
version = 1

[[entities]]
id = "018f6f78-4b6f-74a2-9f8f-5d7f3a8d0001"
name = "Primary Cube"

[entities.components."scrapbot.transform"]
position = [-0.75, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0]
scale = [0.82, 0.82, 0.82]

[entities.components."scrapbot.render.cube"]
color = [0.0, 0.56, 1.0]

[entities.components.spin]
angular_velocity = [0.62, 1.0, 0.0]

[[entities]]
id = "018f6f78-4b6f-74a2-9f8f-5d7f3a8d0002"
name = "Accent Cube"

[entities.components."scrapbot.transform"]
position = [0.86, -0.24, -0.45]
rotation = [0.25, 0.15, 0.0]
scale = [0.42, 0.42, 0.42]

[entities.components."scrapbot.render.cube"]
color = [1.0, 0.62, 0.08]

[entities.components.spin]
angular_velocity = [-0.25, 0.82, 0.4]

[[entities]]
id = "018f6f78-4b6f-74a2-9f8f-5d7f3a8d0100"
name = "Main Camera"

[entities.components."scrapbot.transform"]
position = [0.0, 0.0, 4.8]
rotation = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]

[entities.components."scrapbot.camera"]
fov_y_degrees = 48.0
near = 0.1
far = 100.0

[[entities]]
id = "018f6f78-4b6f-74a2-9f8f-5d7f3a8d0101"
name = "Key Light"

[entities.components."scrapbot.light.directional"]
direction = [0.35, 0.68, 0.64]
color = [1.0, 1.0, 1.0]
intensity = 0.78
ambient = 0.18
