[[entities]]
id = "10000000-0000-4000-8000-000000000001"
name = "Main Camera"

[entities.transform]
position = [0, 2, 6]
rotation = [-0.321751, 0, 0]
scale = [1, 1, 1]

[entities.camera]
fov = 60
near = 0.1
far = 100

[[entities]]
id = "10000000-0000-4000-8000-000000000002"
name = "Ambient Light"

[entities.ambient_light]
color = [1, 1, 1]
intensity = 1

[[entities]]
id = "10000000-0000-4000-8000-000000000003"
name = "Left Cube"

[entities.transform]
position = [-2.25, 0, 0]
rotation = [0, 0, 0]
scale = [1, 1, 1]

[entities.geometry]
resource = "cube"

[entities.material]
resource = "10000000-0000-4000-8000-000000000001"

[entities.components.scrappyphysics.spin]
angular_velocity = [0, 1.5707963, 0]

[entities.components.scrappyphysics.rigidbody]
velocity = [0, 0, 0]

[entities.components.float]
origin = [-2.25, 0, 0]
wave = [0, 1.4, 0.35]

[[entities]]
id = "10000000-0000-4000-8000-000000000004"
name = "Right Cube"

[entities.transform]
position = [1.25, 0, 0]
rotation = [0, 0, 0]
scale = [1, 1, 1]

[entities.geometry]
resource = "cube"

[entities.material]
resource = "10000000-0000-4000-8000-000000000002"

[entities.components.scrappyphysics.spin]
angular_velocity = [0, -1.5707963, 0]

[entities.components.scrappyphysics.rigidbody]
velocity = [0, 0, 0]

[entities.components.float]
origin = [1.25, 0, 0]
wave = [3.1415927, 1.15, 0.3]
