#!/usr/bin/env python3
"""Regenerate Scrapbot's embedded Phosphor icon atlas and Odin symbol table."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/scrapbot/resources/assets/builtin-icons"
ATLAS = ROOT / "src/scrapbot/resources/assets/builtin_icons_mtsdf.bin"
ODIN = ROOT / "src/scrapbot/resources/builtin_icon_data.odin"


def run(command: list[str]) -> None:
    subprocess.run(command, check=True, cwd=ROOT)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in atlas or Odin metadata is stale",
    )
    arguments = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="scrapbot-builtin-icons-") as directory:
        temporary = Path(directory)
        font = temporary / "icons.ttf"
        mapping = temporary / "map.json"
        charset = temporary / "charset.txt"
        atlas = temporary / "atlas.bin"
        layout = temporary / "atlas.json"
        run(
            [
                str(ROOT / "bin/scrapbot-iconc"),
                str(SOURCE),
                "--font-out",
                str(font),
                "--map-out",
                str(mapping),
                "--charset-out",
                str(charset),
            ]
        )
        run(
            [
                os.environ.get("SCRAPBOT_MSDF_ATLAS_GEN", "msdf-atlas-gen"),
                "-font",
                str(font),
                "-charset",
                str(charset),
                "-type",
                "mtsdf",
                "-format",
                "bin",
                "-dimensions",
                "512",
                "512",
                "-size",
                "96",
                "-pxrange",
                "8",
                "-yorigin",
                "top",
                "-imageout",
                str(atlas),
                "-json",
                str(layout),
            ]
        )
        compiler_map = json.loads(mapping.read_text())
        glyphs = {
            glyph["unicode"]: glyph for glyph in json.loads(layout.read_text())["glyphs"]
        }
        lines = [
            "package resources",
            "",
            "// Generated by tools/generate_builtin_icons.py.",
            "BUILTIN_ICON_SYMBOLS := [?]Builtin_Icon_Symbol_Data {",
        ]
        for symbol in compiler_map["symbols"]:
            glyph = glyphs[symbol["codepoint"]]
            atlas_bounds = glyph["atlasBounds"]
            plane_bounds = glyph["planeBounds"]
            uv = [
                atlas_bounds["left"] / 512,
                atlas_bounds["top"] / 512,
                atlas_bounds["right"] / 512,
                atlas_bounds["bottom"] / 512,
            ]
            plane = [
                plane_bounds["left"],
                plane_bounds["top"],
                plane_bounds["right"],
                plane_bounds["bottom"],
            ]
            lines.append(
                '\t{name = "%s", uv = {%s}, plane = {%s}},'
                % (
                    symbol["name"],
                    ", ".join(f"{value:.8f}" for value in uv),
                    ", ".join(f"{value:.8f}" for value in plane),
                )
            )
        lines.extend(["}", ""])
        generated_metadata = temporary / "builtin_icon_data.odin"
        generated_metadata.write_text("\n".join(lines))
        run(["odinfmt", str(generated_metadata), "-w"])
        generated_odin = generated_metadata.read_text()
        if arguments.check:
            if not ATLAS.exists() or atlas.read_bytes() != ATLAS.read_bytes():
                raise SystemExit("built-in icon atlas is stale; run `mise builtin-icons`")
            if not ODIN.exists() or generated_odin != ODIN.read_text():
                raise SystemExit("built-in icon metadata is stale; run `mise builtin-icons`")
            return
        shutil.copyfile(atlas, ATLAS)
        ODIN.write_text(generated_odin)


if __name__ == "__main__":
    main()
