#!/usr/bin/env python3
"""Regenerate Scrapbot's embedded MTSDF atlas and Odin glyph metrics."""

import csv
import pathlib
import subprocess
import sys
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/scrapbot/ui/assets"
ATLAS_SIZE = 512


def main() -> int:
    generator = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path("msdf-atlas-gen")
    atlas = ASSETS / "inter_mtsdf.bin"
    with tempfile.TemporaryDirectory() as temporary_directory:
        csv_path = pathlib.Path(temporary_directory) / "inter_mtsdf.csv"
        subprocess.run(
            [
                str(generator),
                "-font", str(ASSETS / "inter_regular.ttf"),
                "-type", "mtsdf",
                "-format", "bin",
                "-dimensions", str(ATLAS_SIZE), str(ATLAS_SIZE),
                "-size", "48",
                "-pxrange", "8",
                "-yorigin", "top",
                "-imageout", str(atlas),
                "-csv", str(csv_path),
            ],
            check=True,
        )
        with csv_path.open(newline="") as input_file:
            rows = list(csv.reader(input_file))

    lines = [
        "package ui",
        "",
        "// Generated by msdf-atlas-gen 1.4 from Inter 4.1. Do not edit by hand.",
        "FONT_GLYPHS := [FONT_CHAR_COUNT]Font_Glyph{",
    ]
    for row in rows:
        atlas_bounds = [float(value) / ATLAS_SIZE for value in row[6:10]]
        lines.append(
            f"\t{{advance={row[1]},plane={{{','.join(row[2:6])}}},"
            f"uv={{{','.join(map(str, atlas_bounds))}}}}},"
        )
    lines.extend(["}", ""])
    (ROOT / "src/scrapbot/ui/font_data.odin").write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
